/*
 * Interoperability regression, ByteWords/CBOR layer: the first test in this
 * repository to exercise bolos_ux_sskr_hex_check() and
 * bolos_ux_sskr_combine() -- the actual entry points the UI uses once a
 * share has been typed in as ByteWords -- against a vector that was not
 * generated by this port itself.
 *
 * Every other SSKR test either drives the raw Shamir math
 * (sskr_combine_shards(), sskr.c) or feeds shares this port generated
 * itself back into itself. The vector below is the same 128-bit secret as
 * the one in sskr_interop_bc128.c (metadata+value form) -- generated fresh
 * with Blockchain Commons' own bc-sskr (independent from this repository),
 * then manually wrapped in this port's current wire format (CBOR tag
 * 0xD99D75, short-form length byte, standard CRC32) and encoded into
 * ByteWords with this repository's own SSKR_WORDLIST table.
 *
 * Blockchain Commons' published sskr-test-vector.md cannot be used directly
 * at this layer: it uses the now-superseded CBOR tag 309 (0xD90135), while
 * the current spec (bcr-2020-011-sskr.md) and this port both use 40309
 * (0xD99D75). Hence the manual wrap instead of reusing that document's own
 * wire bytes. Its shards are used unchanged one layer down, in
 * sskr_interop_bc128.c, where no CBOR tag is involved.
 *
 * The round trip (bc-sskr generate -> manual CBOR/ByteWords wrap -> decoded
 * back with bc-sskr) was verified before writing this test. Expected
 * secret: 59f2293a5bce7d4de59e71b4207ac5d2, reconstructed from any 2 of the
 * 3 shares below (2-of-3 threshold, single group).
 */

#include <stdarg.h>
#include <stddef.h>
#include <stdbool.h>
#include <setjmp.h>
#include <cmocka.h>
#include <string.h>

#include "testutils.h"
#include "sskr/common_sskr.h"

#define WORDS_PER_SHARE (29)
#define SHARE_COUNT     (3)

static const char *k_share_words[SHARE_COUNT] = {
    "tuna next keep gyro acid able able acid able jump kick math figs stub "
    "legs fish gear yell tiny echo zinc pool lazy hawk brew holy wolf quad "
    "exit",
    "tuna next keep gyro acid able able acid acid claw fish monk iron memo "
    "girl frog apex bulb gift game fizz liar what math surf pool horn keno "
    "inch",
    "tuna next keep gyro acid able able acid also numb yank lava mild kick "
    "also swan ugly door zinc safe news zaps idea taxi ramp tiny gear tuna "
    "figs",
};

static const uint8_t k_expected_secret[16] = {0x59, 0xF2, 0x29, 0x3A, 0x5B,
                                              0xCE, 0x7D, 0x4D, 0xE5, 0x9E,
                                              0x71, 0xB4, 0x20, 0x7A, 0xC5,
                                              0xD2};

/* Decodes WORDS_PER_SHARE space-separated 4-letter ByteWords (as published:
 * a single space between each word) into WORDS_PER_SHARE raw bytes. */
static void decode_share(const char *sentence, uint8_t out[WORDS_PER_SHARE]) {
    const char *word = sentence;

    for (unsigned int i = 0; i < WORDS_PER_SHARE; i++) {
        bool ok = bolos_ux_sskr_byteword_to_hex(
            (const unsigned char *) word, &out[i]);
        assert_true(ok);
        word += SSKR_BYTEWORD_LENGTH + 1;  // skip the word and the space
    }
}

static void test_combine_bc_128bit_bytewords_vector(void **state) {
    (void) state;

    uint8_t share_bytes[SHARE_COUNT][WORDS_PER_SHARE];
    for (unsigned int i = 0; i < SHARE_COUNT; i++) {
        decode_share(k_share_words[i], share_bytes[i]);
    }

    // any 2 of the 3 shares must reconstruct the same secret
    const unsigned int combos[3][2] = {{0, 1}, {0, 2}, {1, 2}};

    for (unsigned int c = 0; c < 3; c++) {
        uint8_t wire[2 * WORDS_PER_SHARE];
        memcpy(&wire[0], share_bytes[combos[c][0]], WORDS_PER_SHARE);
        memcpy(&wire[WORDS_PER_SHARE], share_bytes[combos[c][1]],
               WORDS_PER_SHARE);

        unsigned int valid = bolos_ux_sskr_hex_check(wire, sizeof(wire), 2);
        assert_int_equal(valid, 1);

        uint8_t output[sizeof(k_expected_secret)] = {0};
        unsigned int output_len =
            bolos_ux_sskr_combine(wire, sizeof(wire), 2, output);

        assert_int_equal(output_len, sizeof(k_expected_secret));
        assert_memory_equal(output, k_expected_secret, output_len);
    }
}

int main(void) {
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(test_combine_bc_128bit_bytewords_vector),
    };
    return cmocka_run_group_tests(tests, NULL, NULL);
}
