/*
 * A seeded, reproducible pseudo-random generator for property tests.
 *
 * The suite already has a `cx_rng_no_throw()` in testutils.c, and it is
 * deliberately not a generator at all:
 *
 *     for (size_t i = 0; i < len; i++) {
 *         buffer[i] = (uint8_t) i;
 *     }
 *
 * It writes 0, 1, 2, ... and restarts from zero on every call. That is exactly
 * what the fixed-vector tests need -- tests/sskr.c says so in its header
 * comment ("these tests use a fake random number generator so the shares
 * generated by the tests will be predictable"), and nine test files depend on
 * the shard values it produces. It must not be changed.
 *
 * It is also the worst possible generator for a property test: a property run
 * against it would visit a single degenerate point of the input space over and
 * over while appearing to sweep it, and would stay green against almost any
 * defect. Hence this separate generator, which the SSS/SSKR entry points accept
 * as a parameter (`unsigned char *(*random_generator)(uint8_t *, size_t)`), so
 * nothing shared has to be touched to use it.
 *
 * SplitMix64 (Steele/Lea/Flood, "Fast Splittable Pseudorandom Number
 * Generators"): a fixed sequence of arithmetic on a 64-bit counter, so the
 * whole stream is a pure function of the seed. Sequential seeds produce
 * unrelated streams, which is what lets each iteration of a property be seeded
 * from its own index and replayed on its own from the seed printed in the
 * failure message.
 *
 * Nothing here reads the clock, the environment or any other ambient state: a
 * failing case is reproducible by running the same binary again.
 *
 * Header-only on purpose. Adding this to the shared `testutils` library would
 * relink every one of the pre-existing targets for the benefit of three new
 * ones; a static inline definition per translation unit keeps the blast radius
 * at the files that include it.
 */

#ifndef TESTPRNG_H
#define TESTPRNG_H

#include <stddef.h>
#include <stdint.h>

static uint64_t test_prng_state = 0;

/* Sets the stream. Every later value, and hence every case a property visits,
 * is a function of this and nothing else. */
static inline void test_prng_seed(uint64_t seed) {
    test_prng_state = seed;
}

static inline uint64_t test_prng_next_u64(void) {
    uint64_t z = (test_prng_state += 0x9E3779B97F4A7C15ULL);
    z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ULL;
    z = (z ^ (z >> 27)) * 0x94D049BB133111EBULL;
    return z ^ (z >> 31);
}

/* Uniform on [0, bound), by rejection rather than by a bare modulo: bounds
 * used here (share counts, bit indices, secret lengths) are small enough that
 * modulo bias would concentrate the sampling on the low end of each range. */
static inline uint32_t test_prng_below(uint32_t bound) {
    const uint32_t reject_from = (UINT32_MAX - bound + 1) % bound;
    for (;;) {
        const uint32_t r = (uint32_t) (test_prng_next_u64() >> 32);
        if (r >= reject_from) {
            return r % bound;
        }
    }
}

/* Signature required by sss_split_secret() and sskr_generate_shards(). */
static inline unsigned char *test_prng_fill(uint8_t *buffer, size_t len) {
    size_t i = 0;

    while (i < len) {
        uint64_t chunk = test_prng_next_u64();
        for (size_t j = 0; j < sizeof(chunk) && i < len; j++, i++) {
            buffer[i] = (uint8_t) (chunk & 0xFF);
            chunk >>= 8;
        }
    }
    return (unsigned char *) buffer;
}

#endif /* TESTPRNG_H */
