---
name: Code style check

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
    tags:
      - '**'
  pull_request:

jobs:
  job_lint:
    name: Linter using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_lint.yml@v1
    with:
      source: 'src'

  misspell:
    name: Check misspellings
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_spell_check.yml@v1
    with:
      ignore_words_list: ontop
